name: smart_farming_app
description: A Flutter mobile application that helps farmers make smart, data-driven agricultural decisions using real-time data and AI-assisted logic.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6

  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0

  # Image Picker & Camera
  image_picker: ^1.0.7
  camera: ^0.11.3

  # Local Notifications
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1

  # Storage & Preferences
  shared_preferences: ^2.2.2
  get_storage: ^2.1.1

  # UI & Utilities
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  flutter_launcher_icons: ^0.14.4

  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    # - assets/images/
    # - assets/icons/
    # - assets/locales/

  # Fonts (if needed)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
